#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
V29.2.1 Generic OCR Block Safe Semantic Clean

Goal
- Convert an OCR report from any PDF into a block-level patch map.
- Designed to replace file-specific planners such as CXVIEW-only or LONGMAN-only rules.
- No API call. It only groups OCR text into visual blocks and prepares renderer-compatible patches.

Typical flow
1) OCR already generated by your OCR scanner:
   python ocr_image_region_scanner_v28_1_4_rapidocr_numpyfix.py ... --output-json some_ocr.json

2) Build block-level patch map:
   python auto_patch_planner_v29_2_1_generic_block_safe_semantic_clean.py `
     --ocr-report some_ocr.json `
     --pdf input.pdf `
     --output-patch-map generic_patch_map_v29.json `
     --output-image-region-map generic_image_regions_v29.json `
     --report-json generic_planner_report_v29.json `
     --translation-mode source

3) Render with the existing v27 renderer:
   python pdf_image_region_only_patch_v27_style_presets.py `
     "input.pdf" "output_layout_test.pdf" `
     --patch-map generic_patch_map_v29.json `
     --image-region-map generic_image_regions_v29.json `
     --no-auto-image-rects `
     --font "fonts/NotoSans-Regular.ttf" `
     --font-bold "fonts/NotoSans-Bold.ttf" `
     --font-title "fonts/NotoSans-Bold.ttf" `
     --report-json generic_render_report_v29.json

Notes
- translation-mode=source is for layout test. For real translation, provide --translation-map.
- This planner is intentionally generic: it avoids hard-coded file names, project names, or CXVIEW/LONGMAN slots.
- It groups OCR items into lines, then blocks; patches blocks rather than individual OCR items.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from statistics import median
from typing import Any, Dict, Iterable, List, Optional, Tuple

try:
    import fitz  # PyMuPDF
except Exception:  # pragma: no cover
    fitz = None  # type: ignore

BBox = Tuple[float, float, float, float]

DEFAULT_BRAND_TERMS = {
    # Generic company/brand terms that should usually be preserved, not masked and re-rendered.
    "BFFB", "BOFA", "LONGMAN", "LONGMAN GROUP", "BOFA HOLDING GROUP",
    "GE", "ABB", "SIEMENS", "ALSTOM", "KSB", "SULZER", "FOXBORO", "HONEYWELL",
    "SCHNEIDER", "SCHNEIDER ELECTRIC", "EMERSON", "HOWDEN", "PETROCHINA", "SINOPEC",
    "CNOOC", "SINOMACH", "DBN", "ITG", "DEC", "SDIC", "HARBIN ELECTRIC",
}

UNIT_OR_TECH_TERMS = {
    "MW", "MWH", "KWH", "KW", "KV", "PV", "BESS", "EPC", "O&M", "ESG", "AI", "API", "CCTV", "POS", "RTSP", "ONVIF",
}

BUILTIN_TRANSLATIONS = {
    # Minimal generic dictionary only. Use --translation-map for production translation.
    "Create Social Wealth Bring Happiness to Humanity": "Tạo dựng thịnh vượng xã hội, mang hạnh phúc đến nhân loại",
    "INCORPORATION WITH": "HỢP TÁC VỚI",
    "Thank you": "Xin cảm ơn",
    "Group Performance": "Hiệu suất tập đoàn",
    "Partners / China": "Đối tác / Trung Quốc",
    "Partners / Overseas": "Đối tác / Quốc tế",
    "Renewable Energy": "Năng lượng tái tạo",
    "Project": "Dự án",
    "Power Station Project": "Dự án nhà máy điện",
    "Hydropower Station Project": "Dự án thủy điện",
    "Photovoltaic Engineering Project": "Dự án kỹ thuật quang điện",
}

NOISE_REGEXES = [
    re.compile(r"^[\W_]+$"),
    re.compile(r"^[A-Za-z]$"),
    re.compile(r"^(l|I|i|\||/|\\|_|-|—|–|•|·)$"),
    re.compile(r"^[0-9.,:;\-_/]+$"),
]

CJK_RE = re.compile(r"[\u3400-\u9fff]")


# --- V29.2.1 OCR cleanup / page-level preservation helpers ---
COMMON_EN_STOPWORDS = {
    "the", "and", "for", "with", "from", "that", "this", "has", "have", "was", "were", "are", "is", "it", "its",
    "in", "on", "of", "to", "as", "such", "including", "project", "projects", "power", "station", "group", "market",
    "china", "africa", "asia", "america", "company", "business", "engineering", "energy", "plant", "boiler",
}

# V29.2.1: short grammar tokens must be preserved.
# V29.2 was too aggressive and could drop phrases like "and it is a" or leading "It has".
SAFE_SHORT_TOKENS = {
    "a", "an", "and", "or", "it", "is", "am", "are", "be", "as", "at", "by", "if", "in", "on",
    "of", "to", "for", "from", "the", "we", "us", "uk", "ge", "mw", "kv", "kw", "no", "co", "ltd",
}


def token_clean(tok: str) -> str:
    return re.sub(r"[^A-Za-z0-9×xX&/+.-]", "", tok or "")


def is_gibberish_token(tok: str) -> bool:
    t = token_clean(tok)
    if not t:
        return True
    if re.search(r"\d", t):
        return False
    letters = re.sub(r"[^A-Za-z]", "", t)
    if not letters:
        return True
    if len(letters) <= 2 and t.lower() not in SAFE_SHORT_TOKENS:
        return True
    if len(letters) >= 5 and vowel_ratio(letters) < 0.12:
        return True
    return False


def line_noise_score(line: str) -> float:
    line = norm_text(line)
    if not line:
        return 1.0
    toks = [token_clean(t) for t in line.split() if token_clean(t)]
    if not toks:
        return 1.0
    letters = re.sub(r"[^A-Za-z]", "", line)
    if len(letters) >= 8 and vowel_ratio(letters) < 0.12 and not mostly_numeric_or_code(line):
        return 0.95
    gib = sum(1 for t in toks if is_gibberish_token(t))
    oneish = sum(1 for t in toks if len(re.sub(r"[^A-Za-z]", "", t)) <= 2 and not re.search(r"\d", t))
    knownish = sum(1 for t in toks if t.lower() in COMMON_EN_STOPWORDS or t.lower() in SAFE_SHORT_TOKENS or re.search(r"\d", t))
    score = gib / max(1, len(toks))
    if len(toks) >= 5 and oneish / len(toks) >= 0.55 and knownish <= 1:
        score = max(score, 0.9)
    return score


def strip_gibberish_runs(line: str) -> str:
    raw_toks = line.split()
    if len(raw_toks) < 5:
        return norm_text(line)
    out = []
    run = []
    def flush_run():
        nonlocal run, out
        if len(run) >= 4:
            run = []
        else:
            out.extend(run)
            run = []
    for tok in raw_toks:
        clean = token_clean(tok)
        letters = re.sub(r"[^A-Za-z]", "", clean)
        is_run = False
        if clean and not re.search(r"\d", clean):
            if len(letters) <= 3 and clean.lower() not in COMMON_EN_STOPWORDS and clean.lower() not in SAFE_SHORT_TOKENS:
                is_run = True
            elif len(letters) >= 5 and vowel_ratio(letters) < 0.12:
                is_run = True
        if is_run:
            run.append(tok)
        else:
            flush_run()
            out.append(tok)
    flush_run()
    return norm_text(" ".join(out))


def normalize_ocr_spacing(text: str) -> str:
    text = norm_text(text)
    text = re.sub(r"\bDistributionof\b", "Distribution of", text)
    text = re.sub(r"\bOverseasSubsidiaries\b", "Overseas Subsidiaries", text)
    text = re.sub(r"\bInternationalprojects\b", "International projects", text, flags=re.I)
    text = re.sub(r"\bEastAfrica\b", "East Africa", text)
    text = re.sub(r"\bOceaniaAustralia\b", "Oceania Australia", text)
    text = re.sub(r"\bthan(\d+)", r"than \1", text)
    text = re.sub(r"carriedout", "carried out", text, flags=re.I)
    text = re.sub(r"paower", "power", text, flags=re.I)
    return norm_text(text)



# --- V29.2.1 semantic OCR cleanup helpers ---
OCR_NOISE_TOKENS = {
    "oess", "aina", "ennsy", "ogen", "ounr", "sor", "ddd", "dddds", "uTT".lower(),
    "o--ent", "o-ent", "ggsd", "sd", "oe", "uos", "oss", "oes", "si", "ne",
}

DANGLING_TAIL_WORDS = {"and", "or", "of", "the", "with", "such", "as", "in", "on", "for", "to", "from"}


def semantic_token_key(tok: str) -> str:
    return re.sub(r"[^a-z0-9×x+/-]", "", (tok or "").lower())


def is_semantic_noise_token(tok: str) -> bool:
    k = semantic_token_key(tok)
    if not k:
        return True
    if k in OCR_NOISE_TOKENS:
        return True
    # OCR garbage like gg)sd, o0o, lIl when not numeric/technical.
    letters = re.sub(r"[^a-z]", "", k)
    if len(letters) >= 4 and vowel_ratio(letters) < 0.10 and not re.search(r"\d", k):
        return True
    if len(k) <= 2 and k not in SAFE_SHORT_TOKENS and not re.search(r"\d", k):
        return True
    return False


def trim_dangling_edges(text: str) -> str:
    """Conservative edge trim.

    V29.2 trimmed leading connectors and short grammar words too aggressively, which
    damaged OCR text such as "and it is a comprehensive..." or "It has...".
    V29.2.1 only removes obviously dangling *tail* connectors when the line is long
    enough. It never removes a leading grammar token.
    """
    toks = text.split()
    # Do not trim leading words. OCR may start a valid line with "It", "and", "of", etc.
    # Only trim an obviously dangling tail connector in a sufficiently long line.
    while len(toks) >= 7 and semantic_token_key(toks[-1]) in DANGLING_TAIL_WORDS:
        toks.pop()
    return norm_text(" ".join(toks))


def remove_semantic_noise_runs(line: str) -> Tuple[str, List[str]]:
    """Remove OCR garbage runs while preserving meaningful text before/after the run."""
    notes: List[str] = []
    toks = line.split()
    if not toks:
        return "", notes

    # Drop isolated known noise tokens anywhere, then handle longer runs.
    filtered = []
    for tok in toks:
        k = semantic_token_key(tok)
        if k in OCR_NOISE_TOKENS:
            notes.append(f"drop_noise_token:{tok}")
            continue
        filtered.append(tok)
    toks = filtered
    if not toks:
        return "", notes

    # Remove consecutive semantic-noise runs of length >= 3. If run is in the middle, splice it out.
    out: List[str] = []
    i = 0
    while i < len(toks):
        if is_semantic_noise_token(toks[i]):
            j = i
            while j < len(toks) and is_semantic_noise_token(toks[j]):
                j += 1
            run_len = j - i
            if run_len >= 3:
                notes.append("drop_noise_run:" + " ".join(toks[i:j])[:60])
                i = j
                continue
            # For short noise run at line start/end, drop it too.
            if i == 0 or j == len(toks):
                notes.append("drop_edge_noise:" + " ".join(toks[i:j])[:60])
                i = j
                continue
        out.append(toks[i])
        i += 1

    return trim_dangling_edges(" ".join(out)), notes


def remove_repeated_ngrams(text: str, max_n: int = 8) -> Tuple[str, List[str]]:
    """Remove adjacent repeated word n-grams, useful for OCR line duplication."""
    notes: List[str] = []
    words = text.split()
    if len(words) < 4:
        return text, notes

    def keyseq(seq):
        return [re.sub(r"[^a-z0-9×x+/-]", "", w.lower()) for w in seq]

    changed = True
    guard = 0
    while changed and guard < 8:
        changed = False
        guard += 1
        max_allowed = min(max_n, len(words) // 2)
        for n in range(max_allowed, 1, -1):
            i = 0
            while i <= len(words) - 2 * n:
                a = keyseq(words[i:i+n])
                b = keyseq(words[i+n:i+2*n])
                if a == b and any(a):
                    notes.append("drop_repeated_ngram:" + " ".join(words[i:i+n])[:70])
                    words = words[:i+n] + words[i+2*n:]
                    changed = True
                    break
                i += 1
            if changed:
                break
    return norm_text(" ".join(words)), notes


def semantic_fix_common_ocr(text: str) -> Tuple[str, List[str]]:
    notes: List[str] = []
    original = text
    text = normalize_ocr_spacing(text)

    # Conservative grammar restoration for common OCR-line splits.
    # These are not translations; they restore function words that V29.2 could drop.
    text = re.sub(r"\bBOFA was established on December 1995,\s+comprehensive enterprise\b",
                  "BOFA was established on December 1995, and it is a comprehensive enterprise", text, flags=re.I)
    text = re.sub(r"\bTrade, Commercial Services, Culture and Tourism\s+Financial Services\b",
                  "Trade, Commercial Services, Culture and Tourism and Financial Services", text, flags=re.I)
    text = re.sub(r"\bFour Core Subsidiary Groups\s+has four core subsidiary groups\b",
                  "Four Core Subsidiary Groups It has four core subsidiary groups", text, flags=re.I)
    text = re.sub(r"\bforming\s+diversified development pattern\b",
                  "forming a diversified development pattern", text, flags=re.I)
    text = re.sub(r"\bmarket\s+helping the Group\b", "market and helping the Group", text, flags=re.I)
    text = re.sub(r"\bAdvantages of Global Operation Structure\s+collaborative operation\b",
                  "Advantages of Global Operation Structure The collaborative operation", text, flags=re.I)
    text = re.sub(r"\bforms\s+efficient global layout\b", "forms an efficient global layout", text, flags=re.I)
    text = re.sub(r"\bparticipate\s+international projects\b", "participate in international projects", text, flags=re.I)
    text = re.sub(r"\bAsian countries such as Laos, India, Indonesia, the Philippines,\s+Malaysia, and\b",
                  "Asian countries such as Laos, India, Indonesia, the Philippines, and Malaysia, and", text, flags=re.I)
    text = re.sub(r"\bpower station projects,\s+several\b", "power station projects, such as several", text, flags=re.I)
    text = re.sub(r"\bEnergy Project Expansion\s+has carried out\b", "Energy Project Expansion It has carried out", text, flags=re.I)
    text = re.sub(r"\bin African countries\s+Nigeria and Algeria\b", "in African countries such as Nigeria and Algeria", text, flags=re.I)
    text = re.sub(r"\bmultiple gas\s+waste-to-energy\b", "multiple gas and waste-to-energy", text, flags=re.I)
    text = re.sub(r"\bCooperation\s+has entered\b", "Cooperation It has entered", text, flags=re.I)
    text = re.sub(r"\bparticipated\s+multiple projects\b", "participated in multiple projects", text, flags=re.I)
    text = re.sub(r"\bPower Plant Project\s+Jidong Fuel Ethanol\b", "Power Plant Project for Jidong Fuel Ethanol", text, flags=re.I)
    text = re.sub(r"\bEngineering Project\s+Luoyang\b", "Engineering Project of Luoyang", text, flags=re.I)
    text = re.sub(r"\bIndustry\s+Ltd\., China\b", "Industry Co., Ltd., China", text, flags=re.I)
    text = re.sub(r"\bCoalbed Methane\s+Storage\s+Pressurization Project\s+Hegang\b",
                  "Coalbed Methane Storage and Pressurization Project in Hegang", text, flags=re.I)
    text = re.sub(r"\bPhotovoltaic\s+Substation Engineering\b", "Photovoltaic and Substation Engineering", text, flags=re.I)

    # Common OCR spacing fixes with units and project text.
    text = re.sub(r"\bAfrica(\d+MW)\b", r"Africa \1", text)
    text = re.sub(r"\bAfrica(\d+×?\d*MW)\b", r"Africa \1", text)
    text = re.sub(r"\bthan\s*(\d+)\b", r"than \1", text)
    text = re.sub(r"\bGas-\s+West Africa\s*(\d+MW\s+Gas-)", r"Gas-", text)

    # If OCR duplicated a whole phrase with only spacing errors.
    repeated_patterns = [
        (r"\bWest Africa\s+75MW\s+Gas-\s+West Africa\s*75MW\s+Gas-", "West Africa 75MW Gas-"),
        (r"\bEast Africa\s+4×175MW\s+East Africa\s+4×175MW", "East Africa 4×175MW"),
        (r"\bDistribution of Overseas Subsidiaries\s+Distribution of Overseas Subsidiaries", "Distribution of Overseas Subsidiaries"),
        (r"\bOceania Australia\s+Oceania Australia", "Oceania Australia"),
        (r"\bprojects are spread across more than 30 countries and regions in Asia, Africa, and South\s+projects are spread across", "projects are spread across"),
        (r"\bhydropower and thermal power projects in African countries such as\s+hydropower and thermal power projects in African countries such as", "hydropower and thermal power projects in African countries such as"),
    ]
    for pat, repl in repeated_patterns:
        new = re.sub(pat, repl, text, flags=re.I)
        if new != text:
            notes.append("semantic_regex_dedupe")
            text = new

    text, n2 = remove_repeated_ngrams(text)
    notes.extend(n2)
    text, n3 = remove_semantic_noise_runs(text)
    notes.extend(n3)
    text = trim_dangling_edges(text)
    text = norm_text(text)
    if text != norm_text(original):
        notes.append("semantic_clean_changed")
    return text, notes


def clean_page6_regions_text(text: str) -> str:
    # Better line breaks for map/list style pages.
    t = norm_text(text)
    t = re.sub(r"\bAfrica\s+Nigeria\s+Angola\s+Algeria\s+Senegal\s+Botswana\b", "Africa\nNigeria  Angola\nAlgeria  Senegal\nBotswana", t)
    t = re.sub(r"\bAsia\s+China\s+Malaysia\s+Laos\s+Philippines\s+Uzbekistan\s+Vietnam\s+India\s+Indonesia\s+Pakistan\b", "Asia\nChina  Malaysia  Laos\nPhilippines\nUzbekistan  Vietnam\nIndia  Indonesia\nPakistan", t)
    t = re.sub(r"\bSouth America\s+Brazil\s+Venezuela\b", "South America\nBrazil  Venezuela", t)
    t = re.sub(r"\bOceania\s+Australia\s+Papua New Guinea\b", "Oceania\nAustralia  Papua New Guinea", t)
    return t

def remove_repeated_prefix(text: str) -> str:
    text = normalize_ocr_spacing(text)
    words = text.split()
    if len(words) < 8:
        return text
    low = [re.sub(r"[^a-z0-9]", "", w.lower()) for w in words]
    for n in (4, 3, 2):
        if len(low) < n * 2:
            continue
        prefix = low[:n]
        for i in range(n, min(len(low)-n+1, 22)):
            if low[i:i+n] == prefix:
                return norm_text(" ".join(words[:i] + words[i+n:]))
    for n in range(2, min(7, len(low)//2 + 1)):
        for i in range(0, len(low)-2*n+1):
            if low[i:i+n] == low[i+n:i+2*n]:
                words = words[:i+n] + words[i+2*n:]
                return norm_text(" ".join(words))
    return text


def clean_block_multiline(block: Dict[str, Any]) -> Tuple[str, List[str]]:
    cleaned_lines: List[str] = []
    notes: List[str] = []
    seen: set[str] = set()
    for ln in block.get("lines", []):
        line = norm_text(ln.get("text", ""))
        if not line:
            continue
        original = line
        line = normalize_ocr_spacing(line)
        line = strip_gibberish_runs(line)
        line = remove_repeated_prefix(line)
        line, sem_notes = semantic_fix_common_ocr(line)
        notes.extend(sem_notes)
        if not line:
            notes.append("line_cleaned_empty")
            continue
        score = line_noise_score(line)
        if score >= 0.82 and not mostly_numeric_or_code(line):
            notes.append(f"drop_noisy_line:{original[:60]}")
            continue
        key = norm_key(line)
        if key in seen:
            notes.append(f"drop_duplicate_line:{line[:60]}")
            continue
        seen.add(key)
        cleaned_lines.append(line)
    return "\n".join(cleaned_lines), notes


def detect_partner_logo_pages(raw_items: List[Dict[str, Any]], brand_terms: set[str], page_sizes: Dict[int, Tuple[float, float]], protect_top_band: float) -> Dict[int, str]:
    by_page: Dict[int, List[Dict[str, Any]]] = defaultdict(list)
    for it in raw_items:
        by_page[int(it["page"])].append(it)
    pages: Dict[int, str] = {}
    for page, items in by_page.items():
        title_hit = any("partners" in norm_key(it["text"]) for it in items)
        body_items = [it for it in items if it["bbox"][1] > protect_top_band]
        brand_hits = 0
        card_like = 0
        xs = []
        ys = []
        pw = page_sizes.get(page, (960, 540))[0]
        for it in body_items:
            t = norm_text(it["text"])
            up = t.upper()
            if up in brand_terms or any(up == b or b in up for b in brand_terms if len(b) >= 3):
                brand_hits += 1
            b = it["bbox"]
            if len(t) <= 28 and bbox_w(b) < pw * 0.20:
                card_like += 1
                xs.append(round(center_x(b) / 40) * 40)
                ys.append(round(center_y(b) / 40) * 40)
        if title_hit and (brand_hits >= 4 or card_like >= 8):
            pages[page] = "partner_logo_grid"
        elif brand_hits >= 10 and len(set(xs)) >= 4 and len(set(ys)) >= 2:
            pages[page] = "partner_logo_grid"
    return pages


def allowed_on_partner_page(block: Dict[str, Any]) -> bool:
    text = norm_key(block.get("text", ""))
    b: BBox = block["bbox"]
    return ("partners" in text and b[0] < 280 and b[1] < 190)


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(path: str, data: Any) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def norm_text(s: Any) -> str:
    s = str(s or "").replace("\u00a0", " ").replace("\ufeff", "")
    # Some OCR reports include soft hyphen/control separators.
    s = s.replace("\u00ad", "").replace("\ufffe", "")
    s = re.sub(r"\s+", " ", s).strip()
    return s


def norm_key(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip().lower())


def bbox_tuple(b: Any) -> Optional[BBox]:
    if not isinstance(b, (list, tuple)) or len(b) != 4:
        return None
    try:
        x0, y0, x1, y1 = [float(x) for x in b]
    except Exception:
        return None
    if x1 <= x0 or y1 <= y0:
        return None
    return (x0, y0, x1, y1)


def bbox_union(boxes: Iterable[BBox]) -> BBox:
    boxes = list(boxes)
    return (min(b[0] for b in boxes), min(b[1] for b in boxes), max(b[2] for b in boxes), max(b[3] for b in boxes))


def bbox_w(b: BBox) -> float:
    return max(0.0, b[2] - b[0])


def bbox_h(b: BBox) -> float:
    return max(0.0, b[3] - b[1])


def bbox_area(b: BBox) -> float:
    return bbox_w(b) * bbox_h(b)


def center_y(b: BBox) -> float:
    return (b[1] + b[3]) / 2.0


def center_x(b: BBox) -> float:
    return (b[0] + b[2]) / 2.0


def x_overlap_ratio(a: BBox, b: BBox) -> float:
    inter = max(0.0, min(a[2], b[2]) - max(a[0], b[0]))
    return inter / max(1.0, min(bbox_w(a), bbox_w(b)))


def y_overlap_ratio(a: BBox, b: BBox) -> float:
    inter = max(0.0, min(a[3], b[3]) - max(a[1], b[1]))
    return inter / max(1.0, min(bbox_h(a), bbox_h(b)))


def clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def expanded_bbox(b: BBox, page_size: Optional[Tuple[float, float]], pad_x: float, pad_y: float) -> List[float]:
    x0, y0, x1, y1 = b
    x0 -= pad_x
    y0 -= pad_y
    x1 += pad_x
    y1 += pad_y
    if page_size:
        w, h = page_size
        x0, x1 = clamp(x0, 0, w), clamp(x1, 0, w)
        y0, y1 = clamp(y0, 0, h), clamp(y1, 0, h)
    return [round(x0, 2), round(y0, 2), round(x1, 2), round(y1, 2)]


def is_all_caps(text: str) -> bool:
    letters = [c for c in text if c.isalpha()]
    if len(letters) < 2:
        return False
    return sum(1 for c in letters if c.upper() == c) / len(letters) >= 0.85


def mostly_numeric_or_code(text: str) -> bool:
    chars = [c for c in text if not c.isspace()]
    if not chars:
        return False
    n = sum(1 for c in chars if c.isdigit() or c in "×xX$€£¥%,.+-/():;#&")
    return n / len(chars) >= 0.55


def contains_latin(text: str) -> bool:
    return bool(re.search(r"[A-Za-z]", text))


def vowel_ratio(text: str) -> float:
    letters = re.sub(r"[^A-Za-z]", "", text)
    if not letters:
        return 0.0
    return len(re.findall(r"[aeiouAEIOU]", letters)) / len(letters)


def load_brand_terms(path: Optional[str]) -> set[str]:
    terms = set(DEFAULT_BRAND_TERMS)
    if not path:
        return terms
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Brand keep file not found: {path}")
    for line in p.read_text(encoding="utf-8").splitlines():
        line = norm_text(line)
        if line and not line.startswith("#"):
            terms.add(line.upper())
    return terms


def load_translation_map(path: Optional[str]) -> Dict[str, str]:
    if not path:
        return {}
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Translation map not found: {path}")
    out: Dict[str, str] = {}
    if p.suffix.lower() == ".csv":
        with open(p, "r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                src = norm_text(row.get("source") or row.get("Source") or row.get("english") or row.get("English"))
                tr = norm_text(row.get("translation") or row.get("Translation") or row.get("vietnamese") or row.get("Vietnamese"))
                if src and tr:
                    out[norm_key(src)] = tr
        return out
    data = load_json(str(p))
    if isinstance(data, dict) and isinstance(data.get("translations"), list):
        for item in data["translations"]:
            if not isinstance(item, dict):
                continue
            src = norm_text(item.get("source") or item.get("text") or item.get("english"))
            tr = norm_text(item.get("translation") or item.get("target") or item.get("vietnamese"))
            if src and tr:
                out[norm_key(src)] = tr
    elif isinstance(data, dict):
        for src, tr in data.items():
            src_s, tr_s = norm_text(src), norm_text(tr)
            if src_s and tr_s:
                out[norm_key(src_s)] = tr_s
    return out


def get_page_sizes(pdf_path: Optional[str], ocr_items: List[Dict[str, Any]]) -> Dict[int, Tuple[float, float]]:
    sizes: Dict[int, Tuple[float, float]] = {}
    if pdf_path and fitz is not None and Path(pdf_path).exists():
        doc = fitz.open(pdf_path)
        try:
            for i, page in enumerate(doc):
                sizes[i + 1] = (float(page.rect.width), float(page.rect.height))
        finally:
            doc.close()
    if not sizes:
        # Fallback from OCR extents.
        by_page: Dict[int, List[BBox]] = defaultdict(list)
        for it in ocr_items:
            if it.get("bbox"):
                by_page[int(it["page"])].append(tuple(it["bbox"]))  # type: ignore
        for page, boxes in by_page.items():
            u = bbox_union(boxes)
            sizes[page] = (max(1.0, u[2] + 20), max(1.0, u[3] + 20))
    return sizes


def extract_ocr_items(data: Any) -> List[Dict[str, Any]]:
    raw = []
    if isinstance(data, dict):
        raw = data.get("items") or data.get("ocr_items") or data.get("words") or []
    elif isinstance(data, list):
        raw = data
    out: List[Dict[str, Any]] = []
    for idx, item in enumerate(raw):
        if not isinstance(item, dict):
            continue
        text = norm_text(item.get("text") or item.get("source") or item.get("ocr_text"))
        bbox = bbox_tuple(item.get("bbox") or item.get("box"))
        if not text or not bbox:
            continue
        try:
            page = int(item.get("page") or item.get("page_num") or item.get("pageno") or 0)
        except Exception:
            continue
        if page <= 0:
            continue
        try:
            conf = float(item.get("confidence", item.get("conf", 0.99)))
        except Exception:
            conf = 0.99
        if conf > 1.0:
            conf = conf / 100.0
        out.append({"id": idx, "page": page, "text": text, "bbox": bbox, "confidence": conf})
    return out


def reject_item_reason(
    item: Dict[str, Any],
    page_size: Optional[Tuple[float, float]],
    brand_terms: set[str],
    min_confidence: float,
    min_chars: int,
    protect_top_band: float,
    reject_cjk: bool,
    preserve_brands: bool,
) -> Optional[str]:
    text = item["text"]
    upper = text.upper().strip()
    conf = float(item.get("confidence", 0.0))
    b: BBox = item["bbox"]
    if conf < min_confidence:
        return "low_confidence"
    if reject_cjk and CJK_RE.search(text) and not contains_latin(text):
        return "cjk_preserve"
    if protect_top_band > 0 and b[1] <= protect_top_band:
        # Preserve header/logo band by default. This prevents logo damage on slide decks.
        return "protected_top_band"
    if preserve_brands and (upper in brand_terms or upper in UNIT_OR_TECH_TERMS):
        return "brand_or_unit_preserve"
    if len(text) < min_chars and not mostly_numeric_or_code(text):
        return "too_short"
    for pat in NOISE_REGEXES:
        if pat.match(text):
            return "regex_noise"
    letters = re.sub(r"[^A-Za-z]", "", text)
    if len(letters) >= 6 and vowel_ratio(text) < 0.10 and not mostly_numeric_or_code(text):
        return "no_vowel_noise"
    # Very short uppercase chunks are often partial logos/noise; preserve unless very confident and numeric-ish.
    if is_all_caps(text) and len(letters) <= 5 and not mostly_numeric_or_code(text) and upper not in brand_terms:
        if conf < 0.90:
            return "short_caps_noise"
        return "short_caps_preserve"
    # Huge isolated boxes from OCR mistakes can cover images.
    if page_size:
        pw, ph = page_size
        if bbox_area(b) > 0.10 * pw * ph and len(text) < 25:
            return "oversized_short_noise"
    return None


def build_lines(items: List[Dict[str, Any]], page_sizes: Dict[int, Tuple[float, float]], line_y_factor: float = 0.55) -> List[Dict[str, Any]]:
    by_page: Dict[int, List[Dict[str, Any]]] = defaultdict(list)
    for it in items:
        by_page[int(it["page"])].append(it)
    lines: List[Dict[str, Any]] = []
    for page, page_items in by_page.items():
        heights = [bbox_h(it["bbox"]) for it in page_items if bbox_h(it["bbox"]) > 0]
        med_h = median(heights) if heights else 8.0
        sorted_items = sorted(page_items, key=lambda it: (center_y(it["bbox"]), it["bbox"][0]))
        page_lines: List[List[Dict[str, Any]]] = []
        for it in sorted_items:
            b = it["bbox"]
            best_i = None
            best_score = -1.0
            for i, line in enumerate(page_lines[-20:]):  # only compare recent lines for speed
                idx = len(page_lines) - len(page_lines[-20:]) + i
                lb = bbox_union([x["bbox"] for x in line])
                dy = abs(center_y(b) - center_y(lb))
                yov = y_overlap_ratio(b, lb)
                if yov >= 0.35 or dy <= max(2.5, med_h * line_y_factor):
                    score = yov - dy / max(1.0, med_h)
                    if score > best_score:
                        best_score = score
                        best_i = idx
            if best_i is None:
                page_lines.append([it])
            else:
                page_lines[best_i].append(it)
        # Split each visual line by large horizontal gaps. This matters when OCR reports words,
        # because words from different columns/images can share the same baseline.
        for raw_line_items in page_lines:
            raw_line_items = sorted(raw_line_items, key=lambda it: it["bbox"][0])
            split_groups: List[List[Dict[str, Any]]] = []
            cur: List[Dict[str, Any]] = []
            # A conservative gap threshold: smaller for body text, larger for titles.
            gap_threshold = max(18.0, med_h * 3.2)
            for it in raw_line_items:
                if not cur:
                    cur = [it]
                    continue
                prev = cur[-1]
                gap_x = it["bbox"][0] - prev["bbox"][2]
                # Also split if the new item jumps far after a fairly complete text run.
                if gap_x > gap_threshold:
                    split_groups.append(cur)
                    cur = [it]
                else:
                    cur.append(it)
            if cur:
                split_groups.append(cur)

            for line_items in split_groups:
                text = " ".join(it["text"] for it in line_items)
                text = norm_text(text)
                if not text:
                    continue
                b = bbox_union([it["bbox"] for it in line_items])
                conf = sum(float(it.get("confidence", 0)) for it in line_items) / max(1, len(line_items))
                lines.append({
                    "page": page,
                    "text": text,
                    "bbox": b,
                    "confidence": conf,
                    "items": line_items,
                    "line_count": 1,
                })
    return sorted(lines, key=lambda ln: (ln["page"], ln["bbox"][1], ln["bbox"][0]))


def line_can_join_block(line: Dict[str, Any], block: Dict[str, Any], med_h: float, max_gap: float, min_x_overlap: float) -> Tuple[bool, float]:
    lb: BBox = line["bbox"]
    bb: BBox = block["bbox"]
    # Only attach lines below the current block.
    gap_y = lb[1] - bb[3]
    if gap_y < -med_h * 0.6:
        return False, -999.0
    if gap_y > max_gap:
        return False, -999.0
    xov = x_overlap_ratio(lb, bb)
    left_delta = abs(lb[0] - bb[0])
    center_delta = abs(center_x(lb) - center_x(bb))
    similar_left = left_delta <= max(18.0, med_h * 2.0)
    similar_center = center_delta <= max(45.0, bbox_w(bb) * 0.35)
    if xov >= min_x_overlap or similar_left or similar_center:
        score = xov * 2.0 + (1.0 / (1.0 + gap_y)) + (1.0 / (1.0 + left_delta / max(1.0, med_h)))
        return True, score
    return False, -999.0


def build_blocks(
    lines: List[Dict[str, Any]],
    page_sizes: Dict[int, Tuple[float, float]],
    block_gap_factor: float = 1.10,
    min_x_overlap: float = 0.18,
    max_lines_per_block: int = 8,
) -> List[Dict[str, Any]]:
    by_page: Dict[int, List[Dict[str, Any]]] = defaultdict(list)
    for ln in lines:
        by_page[int(ln["page"])].append(ln)
    blocks: List[Dict[str, Any]] = []
    for page, page_lines in by_page.items():
        heights = [bbox_h(ln["bbox"]) for ln in page_lines if bbox_h(ln["bbox"]) > 0]
        med_h = median(heights) if heights else 8.0
        max_gap = max(4.0, med_h * block_gap_factor)
        active: List[Dict[str, Any]] = []
        for ln in sorted(page_lines, key=lambda x: (x["bbox"][1], x["bbox"][0])):
            best_i = None
            best_score = -999.0
            for i, blk in enumerate(active):
                if int(blk.get("line_count", 1)) >= max_lines_per_block:
                    continue
                ok, score = line_can_join_block(ln, blk, med_h, max_gap, min_x_overlap)
                if ok and score > best_score:
                    best_i, best_score = i, score
            if best_i is None:
                active.append({
                    "page": page,
                    "lines": [ln],
                    "bbox": ln["bbox"],
                    "text": ln["text"],
                    "confidence": ln["confidence"],
                    "line_count": 1,
                })
            else:
                blk = active[best_i]
                blk["lines"].append(ln)
                blk["lines"] = sorted(blk["lines"], key=lambda x: (x["bbox"][1], x["bbox"][0]))
                blk["bbox"] = bbox_union([x["bbox"] for x in blk["lines"]])
                # Keep newline between lines so textbox can preserve paragraph-ish shape.
                blk["text"] = "\n".join(norm_text(x["text"]) for x in blk["lines"])
                blk["confidence"] = sum(float(x.get("confidence", 0)) for x in blk["lines"]) / len(blk["lines"])
                blk["line_count"] = len(blk["lines"])
        blocks.extend(active)
    return sorted(blocks, key=lambda b: (b["page"], b["bbox"][1], b["bbox"][0]))


def classify_block(block: Dict[str, Any], page_size: Optional[Tuple[float, float]], page_median_h: float) -> Dict[str, Any]:
    text = block["text"].replace("\n", " ")
    b: BBox = block["bbox"]
    line_count = int(block.get("line_count", 1))
    h_per_line = bbox_h(b) / max(1, line_count)
    role = "body"
    weight = "regular"
    align = "left"
    if line_count <= 2 and (h_per_line >= max(13.0, page_median_h * 1.25) or is_all_caps(text) or len(text) <= 35):
        role = "title"
        weight = "bold"
    if mostly_numeric_or_code(text) and len(text) <= 20:
        role = "label"
        weight = "bold"
        align = "center"
    if page_size:
        pw, ph = page_size
        # Center-ish title/caption in slide decks.
        if bbox_w(b) < pw * 0.65 and abs(center_x(b) - pw / 2) < pw * 0.18 and line_count <= 3:
            align = "center"
        elif b[0] > pw * 0.65:
            align = "center" if line_count <= 4 else "left"
    font_size = max(4.0, min(26.0, h_per_line * 0.68))
    if role == "title":
        font_size = max(6.0, min(28.0, h_per_line * 0.78))
    elif role == "label":
        font_size = max(4.0, min(18.0, h_per_line * 0.72))
    # Longer translation usually needs a little smaller font.
    if len(text) > 80:
        font_size *= 0.88
    return {"role": role, "weight": weight, "align": align, "font_size": round(font_size, 2)}


def translate_text(text: str, mode: str, translation_map: Dict[str, str], keep_untranslated: bool = True) -> Tuple[str, str]:
    clean = norm_text(text.replace("\n", " "))
    # Keep original line breaks for source mode; translations use paragraph mode unless map value includes newlines.
    if mode == "source":
        return text, "source"
    if norm_key(clean) in translation_map:
        return translation_map[norm_key(clean)], "translation_map"
    if mode in {"dictionary", "builtin", "map_or_builtin"} and clean in BUILTIN_TRANSLATIONS:
        return BUILTIN_TRANSLATIONS[clean], "builtin_dictionary"
    if mode == "blank":
        return "", "blank"
    if keep_untranslated:
        return text, "untranslated_source"
    return "", "missing_translation"


def build_patch_and_regions(
    ocr_report: str,
    pdf: Optional[str],
    output_patch_map: str,
    output_image_region_map: str,
    report_json: str,
    translation_mode: str,
    translation_map_path: Optional[str],
    brand_keep_file: Optional[str],
    min_confidence: float,
    min_chars: int,
    protect_top_band: float,
    reject_cjk: bool,
    preserve_brands: bool,
    block_gap_factor: float,
    min_x_overlap: float,
    max_lines_per_block: int,
    fill_mode: str,
    keep_untranslated: bool,
):
    data = load_json(ocr_report)
    raw_items = extract_ocr_items(data)
    page_sizes = get_page_sizes(pdf, raw_items)
    brand_terms = load_brand_terms(brand_keep_file)
    translation_map = load_translation_map(translation_map_path)
    partner_logo_pages = detect_partner_logo_pages(raw_items, brand_terms, page_sizes, protect_top_band)

    kept_items: List[Dict[str, Any]] = []
    rejected_items: List[Dict[str, Any]] = []
    reject_counter: Counter[str] = Counter()
    for it in raw_items:
        reason = reject_item_reason(
            it,
            page_sizes.get(int(it["page"])),
            brand_terms,
            min_confidence,
            min_chars,
            protect_top_band,
            reject_cjk,
            preserve_brands,
        )
        if reason:
            r = {"page": it["page"], "text": it["text"], "confidence": round(it["confidence"], 3), "bbox": list(it["bbox"]), "reason": reason}
            rejected_items.append(r)
            reject_counter[reason] += 1
        else:
            kept_items.append(it)

    lines = build_lines(kept_items, page_sizes)
    blocks = build_blocks(lines, page_sizes, block_gap_factor=block_gap_factor, min_x_overlap=min_x_overlap, max_lines_per_block=max_lines_per_block)

    # Post-filter blocks that became too tiny/noisy after grouping.
    patches: List[Dict[str, Any]] = []
    rejected_blocks: List[Dict[str, Any]] = []
    method_counter: Counter[str] = Counter()
    by_page_heights: Dict[int, List[float]] = defaultdict(list)
    for ln in lines:
        by_page_heights[int(ln["page"])].append(bbox_h(ln["bbox"]))
    page_median_h = {p: (median(v) if v else 8.0) for p, v in by_page_heights.items()}

    for idx, blk in enumerate(blocks):
        page = int(blk["page"])
        page_size = page_sizes.get(page)
        cleaned_multiline, clean_notes = clean_block_multiline(blk)
        text = norm_text(cleaned_multiline.replace("\n", " "))
        b: BBox = blk["bbox"]
        if page in partner_logo_pages and not allowed_on_partner_page({**blk, "text": text}):
            rejected_blocks.append({"page": page, "text": text[:120], "bbox": list(b), "reason": "partner_logo_page_preserve"})
            continue
        if not text or (len(text) < min_chars and not mostly_numeric_or_code(text)):
            rejected_blocks.append({"page": page, "text": text, "bbox": list(b), "reason": "block_too_short_after_cleaning", "clean_notes": clean_notes[:8]})
            continue
        # Isolated short OCR blocks are usually image/logo noise after word-level OCR.
        # They are dangerous because they create random white/gray patches over photos.
        safe_short_phrases = {"thank you", "contact us", "about us", "partners / china", "partners / overseas"}
        compact_text = norm_key(text)
        if int(blk.get("line_count", 1)) <= 2 and len(text) < 14 and not mostly_numeric_or_code(text) and compact_text not in safe_short_phrases:
            rejected_blocks.append({"page": page, "text": text, "bbox": list(b), "reason": "isolated_short_block"})
            continue
        # Avoid massive accidental blocks.
        if page_size and bbox_area(b) > 0.30 * page_size[0] * page_size[1]:
            rejected_blocks.append({"page": page, "text": text[:120], "bbox": list(b), "reason": "block_too_large"})
            continue
        # Final whole-block semantic pass after line grouping.
        cleaned_multiline2, block_sem_notes = semantic_fix_common_ocr(cleaned_multiline.replace("\n", " "))
        if page == 6:
            cleaned_multiline2 = clean_page6_regions_text(cleaned_multiline2)
        if block_sem_notes:
            clean_notes.extend(block_sem_notes)
            cleaned_multiline = cleaned_multiline2
            text = norm_text(cleaned_multiline.replace("\n", " "))
        translation, method = translate_text(cleaned_multiline, translation_mode, translation_map, keep_untranslated=keep_untranslated)
        if not norm_text(translation):
            rejected_blocks.append({"page": page, "text": text[:120], "bbox": list(b), "reason": "empty_translation"})
            continue
        style = classify_block(blk, page_size, page_median_h.get(page, 8.0))
        # Pad/mask entire block instead of word-level areas.
        line_count = int(blk.get("line_count", 1))
        pad_x = max(2.0, min(10.0, bbox_h(b) * 0.18))
        pad_y = max(1.5, min(8.0, bbox_h(b) * 0.10))
        if line_count > 1:
            pad_y = max(pad_y, 2.5)
        bbox = expanded_bbox(b, page_size, pad_x, pad_y)
        patch = {
            "page": page,
            "source": text,
            "translation": translation,
            "bbox": bbox,
            "role": style["role"],
            "weight": style["weight"],
            "font_size": style["font_size"],
            "min_font_size": max(2.8, round(float(style["font_size"]) * 0.55, 2)),
            "align": style["align"],
            "fill": fill_mode,
            "shape": "rect",
            "pad_x": 0.0,
            "pad_y": 0.0,
            "planner_method": "generic_ocr_block",
            "planner_confidence": round(float(blk.get("confidence", 0.0)), 3),
            "line_count": line_count,
            "ocr_item_count": sum(len(ln.get("items", [])) for ln in blk.get("lines", [])),
            "clean_notes": clean_notes[:8],
            "page_strategy": partner_logo_pages.get(page, "generic_block"),
        }
        patches.append(patch)
        method_counter[method] += 1

    # Full-page allowed regions by default. The planner's own protected-zone logic decides what to patch.
    regions = []
    for page in sorted(page_sizes):
        w, h = page_sizes[page]
        regions.append({
            "page": page,
            "name": f"p{page}_fullpage_v29_generic_allowed",
            "bbox": [0, 0, round(w, 2), round(h, 2)],
            "type": "full_page_allowed_region",
            "note": "Generic block planner output. Protected zones/noise were filtered before patch generation.",
        })

    patch_map = {
        "version": "v29_2_generic_block_semantic_clean_patch_map",
        "created_at": now_iso(),
        "planner": "auto_patch_planner_v29_2_1_generic_block_safe_semantic_clean.py",
        "ocr_report": ocr_report,
        "pdf": pdf,
        "translation_mode": translation_mode,
        "patches": patches,
    }
    region_map = {
        "version": "v29_2_generic_block_semantic_clean_image_regions",
        "created_at": now_iso(),
        "regions": regions,
    }
    report = {
        "version": "v29_2_1_generic_block_safe_semantic_clean_planner_report",
        "created_at": now_iso(),
        "ocr_report": ocr_report,
        "pdf": pdf,
        "ocr_items_total": len(raw_items),
        "ocr_items_kept": len(kept_items),
        "ocr_items_rejected": len(rejected_items),
        "lines_total": len(lines),
        "blocks_total": len(blocks),
        "patches_total": len(patches),
        "rejected_blocks_total": len(rejected_blocks),
        "pages_total": len(page_sizes),
        "translation_mode": translation_mode,
        "translation_methods": dict(method_counter),
        "rejected_items_by_reason": dict(reject_counter),
        "rejected_blocks_by_reason": dict(Counter(x["reason"] for x in rejected_blocks)),
        "partner_logo_pages": {str(k): v for k, v in sorted(partner_logo_pages.items())},
        "patches_by_page": dict(Counter(str(p["page"]) for p in patches)),
        "rejected_items_sample": rejected_items[:80],
        "rejected_blocks_sample": rejected_blocks[:80],
        "note": "No API call. V29.2.1 adds safe semantic OCR cleanup, duplicate phrase cleanup, partner/logo preservation, and keeps short grammar tokens; render with pdf_image_region_only_patch_v27_style_presets.py.",
    }

    save_json(output_patch_map, patch_map)
    save_json(output_image_region_map, region_map)
    save_json(report_json, report)

    print("V29.2.1 Generic OCR Block Safe Semantic Clean summary:")
    print(f"  ocr_report={ocr_report}")
    print(f"  pdf={pdf or ''}")
    print(f"  output_patch_map={output_patch_map}")
    print(f"  output_image_region_map={output_image_region_map}")
    print(f"  report_json={report_json}")
    print(f"  ocr_items_total={len(raw_items)}")
    print(f"  ocr_items_kept={len(kept_items)}")
    print(f"  ocr_items_rejected={len(rejected_items)}")
    print(f"  lines_total={len(lines)}")
    print(f"  blocks_total={len(blocks)}")
    print(f"  patches_total={len(patches)}")
    print(f"  rejected_blocks_total={len(rejected_blocks)}")
    print(f"  partner_logo_pages={len(partner_logo_pages)}")
    print(f"  pages_total={len(page_sizes)}")
    print(f"  translation_mode={translation_mode}")
    print(f"  translation_methods={dict(method_counter)}")
    print(f"  rejected_items_by_reason={dict(reject_counter)}")
    print("  note=No API call. Render with v27 style-preset renderer using the generated patch map and image region map.")


def main():
    ap = argparse.ArgumentParser(description="Generic block-level OCR patch planner for arbitrary PDFs.")
    ap.add_argument("--ocr-report", required=True, help="OCR report JSON containing items with page, text, bbox, confidence.")
    ap.add_argument("--pdf", default=None, help="Original/input PDF. Used for page sizes only.")
    ap.add_argument("--output-patch-map", required=True)
    ap.add_argument("--output-image-region-map", required=True)
    ap.add_argument("--report-json", required=True)
    ap.add_argument("--translation-mode", default="source", choices=["source", "dictionary", "builtin", "map_or_builtin", "blank"], help="source=layout test; map_or_builtin uses --translation-map then built-in dictionary.")
    ap.add_argument("--translation-map", default=None, help="Optional CSV/JSON map: source -> translation.")
    ap.add_argument("--brand-keep-file", default=None, help="Optional txt file with one brand/protected term per line.")
    ap.add_argument("--min-confidence", type=float, default=0.35)
    ap.add_argument("--min-chars", type=int, default=2)
    ap.add_argument("--protect-top-band", type=float, default=95.0, help="Preserve top header/logo band in PDF points. Use 0 to disable.")
    ap.add_argument("--allow-cjk", action="store_true", help="Do not reject CJK-only OCR items. Default rejects/preserves them.")
    ap.add_argument("--no-preserve-brands", action="store_true", help="Allow brand terms to be patched. Default preserves brands/logos.")
    ap.add_argument("--block-gap-factor", type=float, default=1.10)
    ap.add_argument("--min-x-overlap", type=float, default=0.18)
    ap.add_argument("--max-lines-per-block", type=int, default=8)
    ap.add_argument("--fill", default="sample", choices=["sample", "white", "none"], help="Mask/fill mode passed to renderer.")
    ap.add_argument("--drop-missing-translations", action="store_true", help="When using translation modes other than source, skip blocks with no translation instead of keeping source.")
    args = ap.parse_args()

    build_patch_and_regions(
        ocr_report=args.ocr_report,
        pdf=args.pdf,
        output_patch_map=args.output_patch_map,
        output_image_region_map=args.output_image_region_map,
        report_json=args.report_json,
        translation_mode=args.translation_mode,
        translation_map_path=args.translation_map,
        brand_keep_file=args.brand_keep_file,
        min_confidence=args.min_confidence,
        min_chars=args.min_chars,
        protect_top_band=args.protect_top_band,
        reject_cjk=not args.allow_cjk,
        preserve_brands=not args.no_preserve_brands,
        block_gap_factor=args.block_gap_factor,
        min_x_overlap=args.min_x_overlap,
        max_lines_per_block=args.max_lines_per_block,
        fill_mode=args.fill,
        keep_untranslated=not args.drop_missing_translations,
    )


if __name__ == "__main__":
    main()
